# permissions for end users to edit mongodbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mongodb-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mongo-operator
    app.kubernetes.io/part-of: mongo-operator
    app.kubernetes.io/managed-by: kustomize
  name: mongodb-editor-role
rules:
- apiGroups:
  - mongodb.steven.com
  resources:
  - mongodbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mongodb.steven.com
  resources:
  - mongodbs/status
  verbs:
  - get
